### ISSUE TITLE
Excuse me, how to realize the flying point

### ISSUE THREAD

**Issue by helloiam** [artzub/wbgds#2]
Excuse me, how to realize the flying point

thanks

**Comment by artzub** [comment]
Hi! 

[Look please this code](https://github.com/artzub/wbgds/blob/smy/index.html#L1826).
Flying points based on two d3.force layout and setTimeout. 
The code which realizes calculation of animation [starts here](https://github.com/artzub/wbgds/blob/smy/index.html#L384).
You can extract him and apply into your projects.

Now, I'm working on a library that will implement this functionality and will be adjusted flexibly. Deadline is 2 months. You can wait for =)

**Comment by helloiam** [comment]
thank you very much
i very need this library 

I also need thant map  ,  can you working on a  library? 

Waiting for your good news

thanks   :）
